lsp:
  server:
    type: docker
    subtype: image # Or image. container subtype means launching an existing container
    # image subtype means creating a new container each time from a specified image
    name: pyright # Must be unique across all language servers
    server: pyright # Server id of a registered server (by lsp-mode) 
    launch_command: "pyright-langserver --stdio" # Launch command of the language server
    # (selected by a server id specified above) in stdio mode
    # Note: launch_command is not used with container subtype servers
    # as a command is embedded in a container itself and serves as an entrypoint
  mappings:
    - source: "./"
      destination: "/app"
